import {useSelector} from "react-redux"

const translations = {

    de: {

        Logout: "Logout",
        EditProfile: "Profil bearbeiten",
        Contact: "Kontaktieren",
        Delete: "Löschen",
        Report: "Anzeige melden",
        Favorites: "Merken",
        Saved: "Gespeichert",
        Profile: 'Profil',
        MeineAnzeigen: 'Meine Anzeigen',
        Merklist: 'Merklist',
        Nachrichten: 'Nachrichten',
        NochKeineNachrichten:'Noch keine Nachrichten',
        AnmeldungErforderlich: 'Anmeldung erforderlich',
        Schliessen: 'Schließen',
        FindBedienung: 'Finden Sie einen Service in Ihrer Nähe',
        AnzeigeAufgeben: 'Anzeige aufgeben',
        SuchAnzeigen: 'Suchanzeigen',
        KategorieWaehlen: 'Wählen Sie eine Kategorie aus',
        Hallo: 'Hallo',
        NeueAnzeige: 'Neue Anzeige',
        KreuzCreateAnzeige: "Anzeige wirklich abbrechen?\n\nAlle eingegebenen Daten gehen verloren",
        TitelDerAnzeige: 'Titel der Anzeige',
        Biete: 'Ich biete',
        Suche: 'Ich suche',
        PLZ: 'PLZ/Ort',
        BeschreibungAnzeige: 'Beschreibung Ihrer Dienstleistung',
        PreisInfo: 'Preisinfo (optional)',
        FotoAufladen: 'Foto aufladen',
        AnzeigeVeroffentlichen: 'Anzeige veröffentlichen',
        ProzessGeht: 'Veröffentlichen...',
        FotosWerdenVerarbeitet: 'Fotos werden verarbeitet...',
        BilderWerdenKomprimiert: '📷 Bilder werden komprimiert...',
        BittePflichtfelderAusfuellen: 'Bitte Pflichtfelder ausfüllen',
        BitteZuerstEinloggen: 'Bitte zuerst einloggen',
        FiveFoto: 'Sie können maximal 5 Fotos hochladen',
        TwentyMB: 'Die Gesamtgröße der Fotos darf 20 MB nicht überschreiten',
        ErfolgreichVeroeffentlicht: 'Erfolgreich veröffentlicht',
        AnzeigeOnLine: 'Deine Anzeige ist jetzt online',
        Weiter: 'Weiter',
        Dienstleistungen: 'Dienstleistungen',
        NeuesteAnzeigenZuerst: 'Neueste Anzeigen zuerst',
        Alle: 'Alle',
        Angebot: 'Angebot',
        Gesucht: 'Gesucht',
        Deutschlend: 'Deutschland',
        AnzeigeWirdGeladen: 'Anzeige wird geladen...',
        NochKeineAnzeigen: 'Noch keine Anzeigen',
        SeiErste: 'Sei der Erste und veröffentliche dein Angebot',
        AnzeigeErstellen: 'Anzeige erstellen',
        KeineAnzeigenGefunden: 'Keine Anzeigen gefunden',
        Suchradius: 'Versuchen Sie einen größeren Suchradius oder wählen Sie „Deutschland“',
        Oeffnen: 'Öffnen',
        Meldung: '✅ Vielen Dank. Die Meldung wurde gesendet',
        BIETE: 'BIETE',
        SUCHE: 'SUCHE',
        von: 'von',
        ZuKontact: '🔐 Anmelden, um zu kontaktieren',
        DurchTelegram: '🔐 Bitte melden Sie sich über Telegram an',
        Loeschen: ' 🗑 Löschen',
        Bearbeiten: '✏️ Bearbeiten',
        Schreiben: '💬 Kontaktieren',
        Melden: '⚠️ Melden',
        Gespeichert: '❤️ Gespeichert',
        Merken: '🤍 Merken',
        AnzMelden: '⚠️ Anzeige melden',
        Falsch: '⚠️ Irreführende Anzeige',
        Beleidigungen: '🚫 Beleidigungen',
        Abbrechen: 'Abbrechen',
        AnzeigeLoeschen: "Anzeige löschen",
        AnzeigeLoeschenFrage: "Möchten Sie diese Anzeige wirklich löschen?",
        VerbWare:'🚫 Verbotene Ware',
        AnzeigeBearbeiten:'Anzeige bearbeiten',
        ProfilWirdGeladen:'Profil wird geladen...',
        AufWerbungstafelSeit:' 🗓 Auf Werbungstafel seit',
        Anzeigen:'Anzeigen',
        Favoriten:'Favoriten',
        ProfilBearbeiten:'✏️ Profil bearbeiten',
        LogoutProfile: '🚪 Logout',
        Speichern: 'Speichern',
        NochKeineBeschreibung:'Noch keine Beschreibung',
        Deutschland: 'Deutschland',
        Name:'Name',
        UberMich:'Über mich',
        Ort:'Ort',
        DuHastNochKeineAnzeigenErstellt:'Du hast noch keine Anzeigen erstellt',
        DeineMerklisteIstLeer:'Deine Merkliste ist leer',
        AlleChats:'← Alle Chats',
        Nachricht: 'Nachricht...',
        Zuruck: '← Zurück',
        TelegramEoffnen:'Telegram öffnen',


    },

    ru: {

        Logout: "Выйти",
        EditProfile: "Редактировать профиль",
        Contact: "Связаться",
        Delete: "Удалить",
        Report: "Пожаловаться",
        Favorites: "В избранное",
        Saved: "Сохранено",
        Profile: 'Профиль',
        MeineAnzeigen: 'Мои Объявления',
        Merklist: 'Избранное',
        Nachrichten: 'Сообщения',
        AnmeldungErforderlich: 'Авторизация прошла успешно',
        Schliessen: 'Закрыть',
        FindBedienung: 'Найди услугу рядом с собой',
        AnzeigeAufgeben: 'Подать объявление',
        SuchAnzeigen: 'Поиск объявлений',
        KategorieWaehlen: 'Выберите категорию',
        Hallo: 'Приветствую',
        NeueAnzeige: 'Новый Вербунг',
        KreuzCreateAnzeige: 'Удалить Вербунг ?\n\nВсе данные будут потеряны',
        TitelDerAnzeige: 'Название Вербунга',
        Biete: 'Предлагаю',
        Suche: 'Ищу',
        PLZ: 'Почтовый индекс / Город',
        BeschreibungAnzeige: 'Описание',
        PreisInfo: 'Стоимость (не обязательно)',
        FotoAufladen: 'Загрузить фото',
        AnzeigeVeroffentlichen: 'Опубликовать',
        ProzessGeht: 'Публикуется...',
        FotosWerdenVerarbeitet: 'Фотографии загружаются...',
        BilderWerdenKomprimiert: '📷 Фотографии уменьшаются...',
        BittePflichtfelderAusfuellen: 'Заполните обязательные поля',
        BitteZuerstEinloggen: 'Пожалуйста сначала авторизуйтесь !',
        FiveFoto: 'Можно загрузить не более 5 фотографий',
        TwentyMB: 'Общий размер фотографий не должен превышать 20 МБ',
        ErfolgreichVeroeffentlicht: 'Успешно опубликовано',
        AnzeigeOnLine: 'Ваше объявление уже в сети !',
        Weiter: 'Дальше',
        Dienstleistungen: 'Услуги',
        NeuesteAnzeigenZuerst: 'Сначала новые',
        Alle: 'Все',
        Angebot: 'Предложения',
        Gesucht: 'Ищу услугу',
        Deutschlend: 'Германия',
        AnzeigeWirdGeladen: 'Объявления загружаются',
        NochKeineAnzeigen: 'Ещё нет объявлений',
        SeiErste: 'Опубликуйте первое объявление',
        AnzeigeErstellen: 'Создать вербунг',
        KeineAnzeigenGefunden: 'Объвлений не найдено',
        Suchradius: 'Попробуйте выбрать больший радиус поиска или всю Германию',
        Oeffnen: 'Открыть',
        Meldung: '✅ Спасибо Большое. Жалоба Принята',
        BIETE: 'Предлагаю',
        SUCHE: 'Ищу',
        von: 'от',
        ZuKontact: '🔐 Чтобы написать сообщение необходимо авторизоваться',
        DurchTelegram: '🔐 Пожалуйста, авторизуйтесь через телеграм бота',
        Loeschen: ' 🗑 Удалить',
        Bearbeiten: '✏️ Отредактировать',
        Schreiben: '💬 Написать',
        Melden: '⚠️ Пожаловаться',
        Gespeichert: '❤️ Добавлено',
        Merken: '🤍 Добавить',
        AnzMelden: '⚠️ Жалоба на объявление',
        Falsch: '⚠️ Недостоверная Информация',
        Beleidigungen: '🚫 Оскорбления',
        Abbrechen: 'Закрыть',
        AnzeigeLoeschen: "Удаление объявления",
        AnzeigeLoeschenFrage: "Вы действительно хотите удалить это объявление?",
        VerbWare:'🚫 Подозрительная услуга',
        AnzeigeBearbeiten:'Редактирование объявления',
        ProfilWirdGeladen:'Профиль загружается...',
        AufWerbungstafelSeit:' 🗓 На сайте с ',
        Anzeigen:'Объявления',
        Favoriten:'Мерклист',
        ProfilBearbeiten:'✏️ Редактировать профиль',
        LogoutProfile:'🚪 Выйти',
        Speichern: 'Сохранить',
        NochKeineBeschreibung:'Заполнить профиль',
        Deutschland: 'Германия',
        Name:'Имя',
        UberMich:'Обо мне',
        Ort:'Город',
        DuHastNochKeineAnzeigenErstellt:'У Вас ещё нет опубликованных объявлений',
        DeineMerklisteIstLeer:'Нет Вербунгов в Избранном',
        NochKeineNachrichten:'У Вас ещё нет сообщений',
        AlleChats:'← Все чаты',
        Nachricht: 'Сообщение...',
        Zuruck: '← Назад',
        TelegramEoffnen:'Открыть Telegram',
    },

    uk: {
        Logout: "Вийти",
        EditProfile: "Редагувати профіль",
        Contact: "Написати повідомлення",
        Delete: "Видалити",
        Report: "Поскаржитись",
        Favorites: "У вибране",
        Saved: "Збережено",
        Profile: 'Профіль',
        MeineAnzeigen: 'Мої оголошення',
        Merklist: 'Обране',
        Nachrichten: 'Повідомлення',
        AnmeldungErforderlich: 'Авторизація пройшла успішно',
        Schliessen: 'Закрити',
        FindBedienung: 'Знайди послугу поряд із собою',
        AnzeigeAufgeben: 'Подати оголошення',
        SuchAnzeigen: 'Пошук оголошень',
        KategorieWaehlen: 'Вибрати категорію',
        Hallo: 'Привіт',
        NeueAnzeige: 'Нове Оголошення',
        KreuzCreateAnzeige: 'Я справді хочу скасувати цю рекламу?\n\nУсі введені дані будуть втрачені.',
        TitelDerAnzeige: 'Назва оголошення',
        Biete: 'Пропоную',
        Suche: 'Шукаю',
        PLZ: 'Поштовий індекс / Місто',
        BeschreibungAnzeige: 'Опис',
        PreisInfo: "Вартість (не обов'язково)",
        FotoAufladen: 'Завантажити фото',
        AnzeigeVeroffentlichen: 'Опублікувати',
        ProzessGeht: 'Публікується...',
        FotosWerdenVerarbeitet: 'Фотографії завантажуються...',
        BilderWerdenKomprimiert: '📷 Фотографії зменшуються...',
        BittePflichtfelderAusfuellen: 'Заповніть обов\'язкові поля',
        BitteZuerstEinloggen: 'Будь ласка спочатку авторизуйтесь!',
        FiveFoto: 'Можна завантажити не більше 5 фотографій',
        TwentyMB: 'Загальний розмір фотографій не повинен перевищувати 20 МБ',
        ErfolgreichVeroeffentlicht: 'Успішно опубліковано',
        AnzeigeOnLine: 'Ваше оголошення вже в мережі!',
        Weiter: 'Далі',
        Dienstleistungen: 'Послуги',
        NeuesteAnzeigenZuerst: 'Спочатку нові',
        Alle: 'Все',
        Angebot: 'Пропозиції',
        Gesucht: 'Шукаю послугу',
        Deutschlend: 'Німеччина',
        AnzeigeWirdGeladen: 'Оголошення завантажуються...',
        NochKeineAnzeigen: 'Ще немає оголошень',
        SeiErste: 'Опублікуйте перше оголошення',
        AnzeigeErstellen: 'Створити оголошення',
        KeineAnzeigenGefunden: 'Оголошень не знайдено',
        Suchradius: 'Спробуйте вибрати більший радіус пошуку чи всю Німеччину.',
        Oeffnen: 'Відкрити',
        Meldung: '✅ Дякую Велике. Скарга Прийнята',
        BIETE: 'Пропоную',
        SUCHE: 'Шукаю',
        von: 'Від',
        ZuKontact: '🔐 Щоб написати повідомлення, необхідно авторизуватися',
        DurchTelegram: '🔐 Будь ласка, авторизуйтесь через телеграм бота',
        Loeschen: ' 🗑 Видалити',
        Bearbeiten: '✏️ Відредагувати',
        Schreiben: '💬 Написати',
        Melden: '⚠️ Поскаржитись',
        Gespeichert: '❤️ Додано',
        Merken: '🤍 Додати',
        AnzMelden: '⚠️ Скарга на оголошення',
        Falsch: '⚠️ Недостовірна Інформація',
        Beleidigungen: '🚫 Образи',
        Abbrechen: 'Закрити',
        AnzeigeLoeschen: "Видалення оголошення",
        AnzeigeLoeschenFrage: "Ви дійсно хочете видалити це оголошення?",
        VerbWare:'🚫 Підозрювальна послуга',
        AnzeigeBearbeiten:'Редагування оголошення',
        ProfilWirdGeladen:'Профіль завантажується...',
        AufWerbungstafelSeit:' 🗓 На сайті з ',
        Anzeigen:'Оголошення',
        Favoriten:'Вибране',
        ProfilBearbeiten:'✏️ Редагувати профіль',
        LogoutProfile:'🚪 Вийти',
        Speichern: 'Зберегти',
        NochKeineBeschreibung:'Заповнити профіль',
        Deutschland: 'Німеччина',
        Name:"Ім'я",
        UberMich:'Про мене',
        Ort:'Місто',
        DuHastNochKeineAnzeigenErstellt:'У Вас ще немає опублікованих оголошень',
        DeineMerklisteIstLeer:'Пусто',
        NochKeineNachrichten:'У Вас ще немає дописів',
        AlleChats:'← Усі чати',
        Nachricht: 'Повідомлення...',
        Zuruck: '← Назад',
        TelegramEoffnen:'Відкрити Telegram',

    },

    tr: {
        Logout: "Çıkış",
        EditProfile: "Profili düzenle",
        Contact: "bir mesaj yaz",
        Delete: "Silmek",
        Report: "Şikayet etmek",
        Favorites: "Favorilere ekle",
        Saved: "Kaydedildi",
        Profile: 'Profil',
        MeineAnzeigen: 'Reklamlarım',
        Merklist: 'Favoriler',
        Nachrichten: 'Mesajlar',
        AnmeldungErforderlich: 'Yetkilendirme başarılı oldu.',
        Schliessen: 'Kapalı',
        FindBedienung: 'Size en yakın hizmeti bulun',
        AnzeigeAufgeben: 'İlan ver',
        SuchAnzeigen: 'Arama reklamları',
        KategorieWaehlen: 'Bir kategori seçin',
        Hallo: 'Merhaba',
        NeueAnzeige: 'Yeni reklam',
        KreuzCreateAnzeige: 'Bu reklamı gerçekten iptal etmek istiyor muyum?\n\nGirilen tüm veriler kaybolacak.',
        TitelDerAnzeige: 'Reklam Başlığı',
        Biete: 'Öneriyorum',
        Suche: 'Arıyorum',
        PLZ: 'Posta Kodu / Şehir',
        BeschreibungAnzeige: 'Tanım',
        PreisInfo: 'Maliyet (isteğe bağlı)',
        FotoAufladen: 'Fotoğraf yükle',
        AnzeigeVeroffentlichen: 'Yayınla',
        ProzessGeht: 'Yayınlandı...',
        FotosWerdenVerarbeitet: 'Fotoğraflar yükleniyor...',
        BilderWerdenKomprimiert: '📷 Fotoğraflar küçülüyor....',
        BittePflichtfelderAusfuellen: 'Lütfen gerekli alanları doldurun',
        BitteZuerstEinloggen: 'Lütfen önce giriş yapın!',
        FiveFoto: 'Можно загрузить не более 5 фотографий',
        TwentyMB: 'Fotoğrafların toplam boyutu 20 MB\'ı geçmemelidir.',
        ErfolgreichVeroeffentlicht: 'Başarıyla yayınlandı',
        AnzeigeOnLine: 'Reklamınız zaten çevrimiçi!',
        Weiter: 'Daha öte',
        Dienstleistungen: 'Hizmetler',
        NeuesteAnzeigenZuerst: 'Önce yeniler',
        Alle: 'Tüm',
        Angebot: 'Teklifler',
        Gesucht: 'Bir hizmet arıyorum',
        Deutschlend: 'Almanya',
        AnzeigeWirdGeladen: 'Reklamlar yükleniyor...',
        NochKeineAnzeigen: 'Henüz reklam yok.',
        SeiErste: 'İlk ilanınızı yayınlayın',
        AnzeigeErstellen: 'İlan oluştur',
        KeineAnzeigenGefunden: 'Hiç reklam bulunamadı',
        Suchradius: 'Daha geniş bir arama yarıçapı veya tüm Almanya\'yı seçmeyi deneyin.',
        Oeffnen: 'Açık',
        Meldung: '✅ Çok teşekkür ederim. Şikayet kabul edildi',
        BIETE: 'Öneriyorum',
        SUCHE: 'Arıyorum',
        von: 'dan',
        ZuKontact: '🔐 Mesaj yazmak için giriş yapmanız gerekiyor.',
        DurchTelegram: '🔐 Lütfen Telegram botu üzerinden giriş yapın.',
        Loeschen: ' 🗑 Silmek',
        Bearbeiten: '✏️ Düzenle',
        Schreiben: '💬 Yazmak',
        Melden: '⚠️ Şikayet etmek',
        Gespeichert: '❤️ Eklendi',
        Merken: '🤍 Eklemek',
        AnzMelden: '⚠️ Bir reklamla ilgili şikayet',
        Falsch: '⚠️ Yanlış Bilgi',
        Beleidigungen: '🚫 Hakaretler',
        Abbrechen: 'Kapalı',
        AnzeigeLoeschen: "İlanı sil",
        AnzeigeLoeschenFrage: "Bu ilanı gerçekten silmek istiyor musunuz?",
        VerbWare:'🚫 Şüpheli hizmet',
        AnzeigeBearbeiten:'Bir reklamı düzenlemek',
        ProfilWirdGeladen:'Profil yükleniyor...',
        AufWerbungstafelSeit:' 🗓 Sitede ',
        Anzeigen:'Duyurular',
        Favoriten:'Favoriler',
        ProfilBearbeiten:'✏️ Profili düzenle',
        LogoutProfile:'🚪 Çıkış',
        Speichern: 'Kaydetmek',
        NochKeineBeschreibung:'Profilinizi doldurun',
        Deutschland: 'Almanya',
        Name:'İsim',
        UberMich:'Hakkımda',
        Ort:'Şehir',
        DuHastNochKeineAnzeigenErstellt:'Henüz yayınlanmış hiçbir reklamınız yok',
        DeineMerklisteIstLeer:'Boş',
        NochKeineNachrichten:'Henüz hiç mesajınız yok',
        AlleChats:'← Tüm sohbetler',
        Nachricht: 'Mesaj...',
        Zuruck: '← Geri',
        TelegramEoffnen:"Telegram'ı açın",

    }

}

export function useTranslation() {

    const lan =
        useSelector(state => state.user.lan) || "de"

    function t(key) {

        return translations[lan]?.[key] ?? key

    }

    return {t}

}